### ISSUE TITLE
Placed chests sometimes can't be used

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#162]
As of MCL2 0.16.0, placed single chests sometimes can not be used, their inventory slots are unusable and the error log complains about missing node metadata.
This happens rarely, but it happens and is annoying as hell when it happens.
Must be fixed ASAP.

**Comment by Bu-Gee** [comment]
If it helps diagnose:

I placed a single chest and was unable to use it, even after replacing it multiple times.  I made another chest and placed it next to that one and I was able to start using those chests.

Now, even when I was able to use the chest, I still got the message like above with just my location being different.

I will post a link to my video where it happens once I post it.

**Comment by Wuzzy2** [comment]
kwadroke wrote:

> When placing chests & opening them, I sometimes get the following error:
2017-03-26 19:45:09: WARNING[Main]: GUIFormSpecMenu::drawList(): The inventory location "nodemeta:42,27,-97" doesn't exist
> These repeat for as long as the chest is open.
> 
> If I exit and restart Minetest, I then can use the chest properly. This happens if I make a single chest a double chest or just a single chest.
> 
> Using latest commit 277a54a34d7624803ccd7eed9ed23610c05e1414 and Minetest 0.4.15.

**Comment by Wuzzy2** [comment]
I have just made some fixes to the chest metadata. I'm not sure if this fixes the bug, so can you please check with latest development version?

**Comment by Bu-Gee** [comment]
I have done some testing and here is what I have found:

1. All existing chest issues seem to have been fixed.  I used to get the above metadata errors on some existing chests and they are now gone.

2. Placing single chests seem to be working just fine now.  I tested it a few times and didn't get the problem.

3. Placing double chests is now completely broken.  I could not place a double chest in a way where I could use it.

4. Placing a single chest and putting an item in it and then doubling the chest doesn't allow you to double the size of the chest (I don't know if this is desirable or not) and it destroys the items previously placed in the first half of the chest (this can't be desirable).  The new double chest is not usable either.

Here is a video of me doing the testing where I determined the above:  https://youtu.be/ZBf5HxlKw-A?t=22s

**Comment by Wuzzy2** [comment]
I can't reproduce placement issues with large chests. Maybe you somehow grabbed a version while I was still developing.

I have fixed bug number 4.

**Comment by kwadroke** [comment]
Still an issue with the latest commit (01200e921437462f49c361a701b5ab8a750e86e4)

`2017-03-31 19:34:01: WARNING[Main]: GUIFormSpecMenu::drawList(): The inventory location "nodemeta:-72,3,41" doesn't exist`

**Comment by Bu-Gee** [comment]
Sorry for taking so long to get back to you.  For me as of 1e79148e39021ee5ce96ff26ce3e922511891989, it was mostly fixed.

Placing seems to be okay even if the error message does show up.

The only remaining issue is that sometimes you can't place an item in the second placed chest's inventory until you put an item in the first placed chest's inventory.

I was streaming when your last came through and I was able to test it with a video recording: https://youtu.be/n4bR_YJ0xyk?t=45m32s

**Comment by Wuzzy2** [comment]
Interesting fact: I can reliably reproduce problems with large chests (as explained by Bu-Gee) when I place them at -128 and -129 at either the X or Z axis.

Same for:
* (31, 32)
* (15, 16)
* (-1, 0)
* (-17, -16)
* (-33, -32)
* (-49, -48)
* (-65, -64)
* (-81, -80)

And so on. It seems it happens at an interval of 16.

I'm starting to suspect a Minetest bug here, at least partially.

But this does not yet explain the weirdness with single chests. :-(

**Comment by Wuzzy2** [comment]
After a very, very long debugging period, I came to the conclusion that this bug or at least a part of the bug is caused by Minetest:
https://github.com/minetest/minetest/issues/5894

**Comment by Wuzzy2** [comment]
Oh my! I think I have a workaround for the double chest bug. MAYBE it also fixes all the other chest-related bugs. FINALLY! This bug was so annoying.

@Bu-Gee, @kwadroke: I would appreciate it if you could check if any chest bugs still occour in the current development version. If I don't see evidence of this bug in the next few days, I consider it fixed.

**Comment by Wuzzy2** [comment]
I think this is fixed now.

**Comment by Wuzzy2** [comment]
No, this isn't a chest bug.
The actual problem are the villages, they are still experimental and don't initialize chests and furnaces. Villages don't appear naturally, the biggest problem is that they are completely flat and aren't random at all.

I have now removed all chests and furnaces from villages and added a warning for `/spawnstruct village`.
